### ISSUE TITLE
Request: Additional Nether brightness option

### ISSUE THREAD

**Issue by ghost** [JayAvery/accesstweaks#1]
Everything in my game is beautiful; skies are bright and caves are dark. Everything else on my computer looks good. But when I go into the nether I have to spam torches to see anything, especially in fortresses.

**Comment by averixus** [comment]
Thanks for the feature request (my first ever github 'issue'!). I believe the apparent brightness in the nether is artificially lowered in vanilla, so that it always appears darker than the same light level in the overworld. I'm definitely going to look into this and see if it's possible to make the nether brightness equivalent to the overworld.

**Comment by ghost** [comment]
Thanks.
